runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /_ah/api/.*
    script: app.app

libraries:
  - name: pycrypto
    version: 2.6.1
  - name: ssl
    version: 2.7.11

builtins:
  - appstats: on
